extends:
    - next
    - next/core-web-vitals
    - eslint:recommended
    # - next/babel
    - prettier
    - plugin:@typescript-eslint/eslint-recommended
    - plugin:@typescript-eslint/recommended
parserOptions:
    project: ./tsconfig.json
ignorePatterns:
    - node_modules
    - dist
    - "**/*.js"
rules:
    no-undef: # TypeScriptのコンパイラが未定義はエラーにしてくれるため
        - off
