{
  "extends": [
    "next",
    "next/core-web-vitals" 
    #"next/babel"
    #"prettier",
  ],
  "ignorePatterns": ["node_modules", "dist"],
  "parserOptions": {
    "babelOptions": {
      "presets": ["require.resolve(\"next/babel\")"]
    }
  },
  "rules": {
    "camelcase": ["error", { "properties": "never" }],
    "no-unreachable": "error"
  }
}
